### PR TITLE
mediawiki: Be even more specific about where cookies are valid

### PR DESCRIPTION
**Pull request by yuvipanda**
- Only on the callback URL!
- Can not be read from JS!

Securitayh! Do not leak the secure cookie as much as possible

### CODE REVIEW

**Comment by yuvipanda** [comment]
Travis seems misconfigured? Uses rake?!

**Comment by yuvipanda** [comment]
Hmm, this is actually failing to read the cookies in the callback, not fully sure why. I see that the cookie header is being sent...

**Comment by yuvipanda** [comment]
Ah, had just missed a few more commits. Works fine now :)

**Comment by rgbkrk** [comment]
Looks like the case of a not existing .travis.yml yet Travis was enabled on the repo.

**Comment by rgbkrk** [comment]
Added a simple `.travis.yml` in #27 that installs the package and makes sure that the import works. If you rebase, you'll get the .travis.yml. Otherwise, it's not a big deal - this wasn't being tested before.

**Comment by yuvipanda** [comment]
@rgbkrk ok, I've rebased now :)

**Comment by rgbkrk** [comment]
Ok, cool.

**Comment by rgbkrk** [comment]
On another note, I think we should welcome you aboard in helping maintain this plugin so you're not blocked on mediawiki things. I'm going to add you as a collaborator.

**Pull request merged**
